server:
  port: 9090

spring:

  datasource:
    generate-unique-name: false
    username: root
    password: fathi09SF@
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size:   50

  profiles:
    active:
      - production

  servlet:
    multipart:
      max-file-size: 10MB

dumbo:
  upload-path: image-storage

---
spring:
  profiles: production

  datasource:
    url: jdbc:h2:./media
    username: root
    password: fathi09SF@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles: development